version: '3.8'

services:
  backend:
    build:
      context: ./project-backend
    ports:
      - "3001:3001"
    volumes:
      - ./project-backend:/usr/src/app
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./project-frontend
    ports:
      - "3001:80"
    volumes:
      - ./project-frontend:/usr/src/app
    environment:
      - NODE_ENV=development
